using HrcTech.Application.Exceptions;
using HrcTech.Application.Interfaces;
using HrcTech.Application.Settings;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;

namespace HrcTech.Infrastructure.Storage;

public sealed class LocalFileStorage : IFileStorage
{
    private readonly string _root;
    private readonly ILogger<LocalFileStorage> _logger;

    public LocalFileStorage(IOptions<StorageOptions> options, ILogger<LocalFileStorage> logger)
    {
        _logger = logger;

        if (string.IsNullOrWhiteSpace(options.Value.RootPath))
            throw new InvalidOperationException("Storage:RootPath is not configured.");

        _root = Path.TrimEndingDirectorySeparator(Path.GetFullPath(options.Value.RootPath));
        Directory.CreateDirectory(_root);
    }

    public async Task SaveAsync(string relativePath, Stream content, long maxBytes, CancellationToken ct)
    {
        var full = Resolve(relativePath);
        Directory.CreateDirectory(Path.GetDirectoryName(full)!);

        try
        {
            await using var target = new FileStream(full, FileMode.CreateNew, FileAccess.Write, FileShare.None, 81920, useAsync: true);
            var buffer = new byte[81920];
            long total = 0;
            int read;

            while ((read = await content.ReadAsync(buffer, ct)) > 0)
            {
                total += read;
                if (total > maxBytes) throw new PayloadTooLargeException("The file is too large.");
                await target.WriteAsync(buffer.AsMemory(0, read), ct);
            }
        }
        catch
        {
            TryDeleteFile(full);   // never leave a partial upload behind
            throw;
        }
    }

    public async Task<byte[]> ReadHeaderAsync(string relativePath, int count, CancellationToken ct)
    {
        await using var stream = new FileStream(Resolve(relativePath), FileMode.Open, FileAccess.Read, FileShare.Read, 4096, useAsync: true);
        var buffer = new byte[count];
        var total = 0;

        while (total < count)
        {
            var read = await stream.ReadAsync(buffer.AsMemory(total, count - total), ct);
            if (read == 0) break;
            total += read;
        }

        return buffer[..total];
    }

    public string GetPhysicalPath(string relativePath) => Resolve(relativePath);

    public bool Exists(string relativePath) => File.Exists(Resolve(relativePath));

    public long GetSize(string relativePath) => new FileInfo(Resolve(relativePath)).Length;

    public void Delete(string relativePath) => TryDeleteFile(Resolve(relativePath));

    public void DeleteDirectory(string relativeDirectory)
    {
        var full = Resolve(relativeDirectory);
        try
        {
            if (Directory.Exists(full)) Directory.Delete(full, recursive: true);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Could not delete storage directory {Directory}.", relativeDirectory);
        }
    }

    public string CreateTempDirectory()
    {
        var dir = Path.Combine(_root, "tmp", Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(dir);
        return dir;
    }

    public void DeleteTempDirectory(string physicalPath)
    {
        var tempRoot = Path.Combine(_root, "tmp") + Path.DirectorySeparatorChar;
        var full = Path.GetFullPath(physicalPath);

        if (!full.StartsWith(tempRoot, StringComparison.OrdinalIgnoreCase)) return;   // only ever touch tmp

        try
        {
            if (Directory.Exists(full)) Directory.Delete(full, recursive: true);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Could not delete temp directory.");
        }
    }

    public void AdoptFile(string sourcePhysicalPath, string relativeTarget)
    {
        var target = Resolve(relativeTarget);
        Directory.CreateDirectory(Path.GetDirectoryName(target)!);
        File.Move(sourcePhysicalPath, target, overwrite: false);
    }

    // All paths are generated by the server, but we still refuse anything that escapes the root.
    private string Resolve(string relativePath)
    {
        var full = Path.GetFullPath(Path.Combine(_root, relativePath));
        if (!full.StartsWith(_root + Path.DirectorySeparatorChar, StringComparison.OrdinalIgnoreCase))
            throw new InvalidOperationException("Invalid storage path.");

        return full;
    }

    private void TryDeleteFile(string fullPath)
    {
        try
        {
            if (File.Exists(fullPath)) File.Delete(fullPath);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Could not delete a stored file.");
        }
    }
}